### ISSUE TITLE
What to use as the home screen?

### ISSUE THREAD

**Issue by ryasmi** [chrisandryan/Budgeter#6]
In terms of a home screen, can't we just put them on the transactions page straight away?

**Comment by ryasmi** [comment]
@chrisandryan: "Hard to say really looking at your budgets is also really important"  
**me**: "and so is looking at your accounts though to be honest"  
@chrisandryan: "I think budgets screen should be home"  
**me**: "Maybe we should just start them on the budgets screen, then just put them on which ever page they were on last?"  
@chrisandryan: "Yeah definitely an option."

**Comment by ryasmi** [comment]
@chrisandryan So it sounds like we will need a home screen. I'm thinking we add another circle at the bottom and allow users to swipe to get to the home screen. To avoid the swiping to remove problem, I think we should have hold to edit and then swipe to delete (or hold again to stop editing - alternatively we can have another screen for editing).

**Comment by ghost** [comment]
What would be on the home screen though other than links to the other 3 pages?

If it's their first time using the app then definitely take them into budgets and through a tutorial of all the screens.
Otherwise can we store the last page they were on in a table in the database?  Just update the record when they swipe to a new page.  If we can't do something like that then take them to the page they are likely to use the app for most, which should also be the middle of the three page layout.  I would assume this would be transactions?

**Comment by ryasmi** [comment]
I think we have decided somewhat implicitly that the transactions will probably be the home screen, users will swipe to switch between screens (and the current screen will be shown by the 3 dots - however as we found when getting concept feedback we should probably put the context/screen name under the dots or something). We are adding a "-" button to the top bar to remove all selected items on the current screen (therefore we have no need for a remove/edit gesture). I think these discussions can be found on the version 3 drawings on google drive. If you give me the email you use for google drive @chorley I'll give you access to the folder or @chrisandryan should be able to do it.
